-- MySQL Script generated by MySQL Workbench
-- 06/03/17 13:12:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema online_judge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_judge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_judge` DEFAULT CHARACTER SET utf8 ;
USE `online_judge` ;

-- -----------------------------------------------------
-- Table `online_judge`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `sex` TINYINT(1) NULL DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online_judge`.`advisors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`advisors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uid_user` INT(11) NULL DEFAULT NULL,
  `uid_admin` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `advisors_id_uindex` (`id` ASC),
  UNIQUE INDEX `advisors_uid_user_uid_admin_uindex` (`uid_user` ASC, `uid_admin` ASC),
  INDEX `fk_adv_use_adm` (`uid_admin` ASC),
  CONSTRAINT `fk_adv_use_adm`
    FOREIGN KEY (`uid_admin`)
    REFERENCES `online_judge`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_adv_use_use`
    FOREIGN KEY (`uid_user`)
    REFERENCES `online_judge`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 76
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online_judge`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `categories_name_uindex` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online_judge`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`questions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `qid` INT(11) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `cid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `qid_UNIQUE` (`id` ASC),
  INDEX `fk_que_cat_nam_idx` (`cid` ASC),
  CONSTRAINT `fk_que_cat_cid`
    FOREIGN KEY (`cid`)
    REFERENCES `online_judge`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online_judge`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`scores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` INT(11) NOT NULL,
  `cid` INT(11) NULL DEFAULT NULL,
  `usual_score` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `score_id_uindex` (`id` ASC),
  INDEX `fk_sco_use_uid` (`uid` ASC),
  INDEX `fk_sco_cat_cid` (`cid` ASC),
  CONSTRAINT `fk_sco_cat_cid`
    FOREIGN KEY (`cid`)
    REFERENCES `online_judge`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sco_use_uid`
    FOREIGN KEY (`uid`)
    REFERENCES `online_judge`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online_judge`.`test_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`test_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `qid` INT(11) NOT NULL,
  `input` TEXT NOT NULL,
  `output` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `test_data_id_uindex` (`id` ASC),
  INDEX `fk_ted_que_qid` (`qid` ASC),
  CONSTRAINT `fk_ted_que_qid`
    FOREIGN KEY (`qid`)
    REFERENCES `online_judge`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `online_judge`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`tests` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `uid` INT(11) NOT NULL,
  `qid` INT(11) NOT NULL,
  `submit_time` DATETIME NOT NULL,
  `code` TEXT NULL DEFAULT NULL,
  `correct_rate` DOUBLE NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tests_id_uindex` (`id` ASC),
  INDEX `fk_student_test_info_sid_idx` (`uid` ASC),
  INDEX `fk_tes_use_sid_idx` (`qid` ASC),
  CONSTRAINT `fk_tes_que_qid`
    FOREIGN KEY (`qid`)
    REFERENCES `online_judge`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tes_use_uid`
    FOREIGN KEY (`uid`)
    REFERENCES `online_judge`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
